/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Message.Message;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author Ceren
 */
public class ChatFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChatFrame
     */
    
    public DefaultListModel dlm = new DefaultListModel();


    public ChatFrame() {
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        initComponents();
        jList1.setModel(dlm);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        chatText = new javax.swing.JTextField();
        sendDocument = new javax.swing.JButton();
        sendMessage = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        refreshClients = new javax.swing.JButton();
        roomlbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(690, 490));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("|COMPORDER");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 150, 30));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("CHAT APP|");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, 30));

        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)), "Clients List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(51, 102, 255))); // NOI18N
        jList1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jList1.setForeground(new java.awt.Color(51, 102, 255));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 160, 220));
        jPanel1.add(chatText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 250, 30));

        sendDocument.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ceren\\Downloads\\clip (1).png")); // NOI18N
        sendDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendDocumentActionPerformed(evt);
            }
        });
        jPanel1.add(sendDocument, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 30, 30));

        sendMessage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ceren\\Downloads\\send (2) (1).png")); // NOI18N
        sendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageActionPerformed(evt);
            }
        });
        jPanel1.add(sendMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 30, 30));

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ceren\\Downloads\\happy-face (2).png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 30, 30));

        refreshClients.setBackground(new java.awt.Color(51, 102, 255));
        refreshClients.setForeground(new java.awt.Color(255, 255, 255));
        refreshClients.setText("Refresh");
        refreshClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshClientsActionPerformed(evt);
            }
        });
        jPanel1.add(refreshClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 160, -1));
        jPanel1.add(roomlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 90, 20));

        messageArea.setColumns(20);
        messageArea.setRows(5);
        messageArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jScrollPane2.setViewportView(messageArea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 370, 210));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendDocumentActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int selection = fileChooser.showOpenDialog(this);
        
        File file = null;
        // keep selected file from chooser in file variable
        if (selection == JFileChooser.APPROVE_OPTION)
            file = fileChooser.getSelectedFile();
        
        byte fileContent[] = new byte[(int)file.length()];
        try {
            BufferedInputStream bis = new BufferedInputStream(new FileInputStream(file));
            bis.read(fileContent, 0, fileContent.length);
            Message fileMSG = new Message(Message.messageType.ROOM_FILE);
            fileMSG.fileContent = fileContent;
            fileMSG.content = file.getName(); // msg.content == file name
            Client.sendRequest(fileMSG);
            System.out.println("Sended file path: "+file.getAbsolutePath());
            
            // notifying to message sended by who
            String sender = LoginFrame.menuFrame.jLabel1.getText().substring(3, LoginFrame.menuFrame.jLabel1.getText().length()-1);
            Message notifyFileMSG = new Message(Message.messageType.ROOM_FILE_NOTIFY);
            notifyFileMSG.content = sender.toUpperCase() + ": " + file.getName() + " shared";
            Client.sendRequest(notifyFileMSG);
            
        } catch (FileNotFoundException ex) {
            System.out.println("File not found.. "+ex);
        } catch (IOException ex) {
            System.out.println("File read exception.."+ex);
        }
    }//GEN-LAST:event_sendDocumentActionPerformed

    private void sendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageActionPerformed
        // TODO add your handling code here:
        if (chatText.getText() != null) {
            Message msg = new Message(Message.messageType.TEXT);
            msg.content = chatText.getText();
            Client.sendRequest(msg);
        }
        chatText.setText("");
    }//GEN-LAST:event_sendMessageActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void refreshClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshClientsActionPerformed
        // TODO add your handling code here
        System.out.println("refresh clickeddd");
        Message refreshMessage = new Message(Message.messageType.REFRESH);
        refreshMessage.content = roomlbl.getText().toLowerCase();
        System.out.println("refresh message.content : "+refreshMessage.content);
        Client.sendRequest(refreshMessage);
    }//GEN-LAST:event_refreshClientsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chatText;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea messageArea;
    private javax.swing.JButton refreshClients;
    public javax.swing.JLabel roomlbl;
    private javax.swing.JButton sendDocument;
    private javax.swing.JButton sendMessage;
    // End of variables declaration//GEN-END:variables
}
